development:
  adapter: postgresql
  encoding: unicode
  database: Hello_development
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: Hello_test
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: Hello_production
  pool: 5